# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "en-US"
title: NOC Thoughts
subtitle: Mad Rantings of a Caffeine Addicted Engineer
email: nocthoughts@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  NOC Thoughts -  authored by Ken Perry - is a blog for interesting issues, lessons learned, useful scripts and more in Cisco's Unified Communicationsland of fun... and bugs. Lots of bugs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

repository: "UnHall0w3d/UnHall0w3d.github.io"

# Theme settings
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
teaser: /assets/images/mainpicture_mountains.jfif
logo: /assets/images/icon.png
search: true
og_image: /assets/images/mainpicture_mountains.jfif
atom_feed:
  hide: true

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-30994747-1"
    anonymize_ip: false

# SEO
bing_site_verification: ""

# Social sharing
twitter_username: thoughtsnoc
github_username: UnHall0w3d
linkedin_username: kperryuc
social:
  name: Kenneth Perry
  links:
    - https://twitter.com/thoughtsnoc
    - https://www.linkedin.com/in/kperryuc
    - https://github.com/UnHall0w3d

# Site author
author:
  name: "Kenneth Perry"
  location: "Syracuse, NY"
  avatar: "/assets/images/author-avatar.jpg"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/UnHall0w3d"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kperryuc"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/thoughtsnoc"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/VSAJUEyRjC"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Outputting
output_ext: .html
permalink: /:year/:month/:day/:title:output_ext
paginate: 10
paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      show_date: true
      toc: true
      toc_sticky: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development